### ISSUE TITLE
Caller of plugin readmore.py fails to close <span> tag

### ISSUE THREAD

**Issue by hfath** [pyblosxom/pyblosxom#49]
A combination of the 'gray' flavour and the readmore.py plugin, statically rendered, gives me 

`XML Parsing Error: mismatched tag. Expected: </span>.`
`Location: https://some.host/blog/index.gray`
`Line Number 107, Column 3:</div>`
`--^`

(full source on request.)

The culprit, I think, is the line

&lt;pre&gt;
&lt;p&gt;&lt;span class="caps"&gt;&lt;p class="readmore"&gt;&lt;a href="https://some.host/blog/test/lorem_ipsum.gray"&gt; read more... &lt;/a&gt;&lt;/p&gt;
&lt;/pre

where a `<span>` tag is left open without a closing `</span>`.  The `<p class="readmore"> ... </p>` is provided by the readmore_template property; the rest of the line is generated somewhere else, by whoever calls the plugin.

What is the way to debug this within pyblosxom?

And is there a way to tell this bug tracker that it should not render html code?

**Comment by hfath** [comment]
I should mention that the plugin pipeline is

`py["load_plugins"] = ["readmore", "rst_parser", "txtl"]`

-- and the `<span class="caps">` sequence is from textile.py, but it looks correct there. So something else is playing with it later...

**Comment by AkaiKitsune** [comment]
You can run the whole thing in a debugger (Pycharm is nice!) and step through it.

This guide should help with that: http://pyblosxom.github.io/Documentation/1.5/dev_hacking.html#installation

What version of Pyblosxom (and what version of Python ) are you running?
I'm happy to help you by checking it out as well, but I can't find the textile plugin you are using?  Am I just missing something, or did you make it?

I'm guessing the program is as you suspected, an interaction between the plugins.

**Comment by hfath** [comment]
My environment is python 2.7, pyblosxom 1.5.3 with static rendering. 

I cannot quite remember where I picked up the txtl.py textile wrapper plugin; I put it at [https://github.com/hfath/plugins/blob/master/textile/txtl.py](url).

Is there a defined sequence for executing plugins, or is every plugin supposed to not step on others' turf? I guess I might just play with that...

**Comment by hfath** [comment]
The problem is in readmore.py: When it decides to hide the rest of an entry, it replaces everything from the start of the breakpoint expression to the end of the entry with the content of readmore_template. 

Now, if the breakpoint is wrapped in html tags by whatever markdown plugin used, the closing tags get lost. Assuming the breakpoint expression is on a line by its own, I could cut off from the end of this line - but how to detect it?

**Comment by hfath** [comment]
I nailed it with regexp groups, appending everything till the next `</p>` 

`match = re.search('(' + breakpoint + ')(.*?</[pP]>)', entry["body"])`
`[...]`
`entry["body"] = entry["body"][:match.start(0)] + link +  str(match.group(2))`

-- there must be a more robust way than hand-parsing a html tag, though?

**Comment by hfath** [comment]
Well, I spoke too soon -- using the readmore plugin without any markdown involved, there will be no surrounding `<p> </p>` to match on. 

I think I want "the rest of the line up to, but excluding, the first opening tag". Negative lookahead assertions [https://docs.python.org/2/howto/regex.html#lookahead-assertions](url) might help.

**Comment by AkaiKitsune** [comment]
It sounds like you have it well in hand. I'd love to see what you come up with.
It seems like the licence is clear enough too, so we should prob add it to the plugin listing.

**Comment by hfath** [comment]
[https://travis-ci.org/pyblosxom/pyblosxom/builds/273307308?utm_source=github_status&utm_medium=notification](url) - now for fixing the test...

**Comment by AkaiKitsune** [comment]
Let me know when  you have a passing version :-)

**Comment by hfath** [comment]
Ping -- see #50
